<?xml version="1.0" encoding="utf-8"?><Database Name="itcommunity" EntityNamespace="ITCommunity" ContextNamespace="ITCommunity" Class="DatabaseLinqBase" Modifier="Abstract" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PETCH-PC;Initial Catalog=itcommunity;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Petch-PC" Provider="System.Data.SqlClient" />
  <Table Name="dbo.comments" Member="Comments">
    <Type Name="Comment" Id="ID1">
      <Column Name="id" Member="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="post_id" Member="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Member="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cdate" Member="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ip" Member="Ip" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="text" Member="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.CommentAdd" Method="CommentAdd">
    <Parameter Name="post_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="user_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="ip" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="text" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.CommentUpdate" Method="CommentUpdate">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="text" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CommentDel" Method="CommentDel">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CommentGetByAuthor" Method="CommentGetByAuthor">
    <Parameter Name="author_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="total_records" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.CommentGetById" Method="CommentGetById">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.CommentGetByPost" Method="CommentGetByPost">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.CommentGetLasts" Method="CommentGetLasts">
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
</Database>