<?xml version="1.0" encoding="utf-8"?><Database Name="itcommunity" EntityNamespace="ITCommunity.Db.Models" ContextNamespace="ITCommunity.Db" Class="Database" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WIN7\SQLEXPRESS;Initial Catalog=itcommunity;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="win7" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CaptchaAnswers" Member="CaptchaAnswers">
    <Type Name="CaptchaAnswer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CaptchaId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsRight" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Captcha_CaptchaAnswer" Member="Captcha" ThisKey="CaptchaId" OtherKey="Id" Type="Captcha" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User" Id="ID2">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nick" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="UserRoles" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Column Name="CanAddHeader" Type="bool" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="HeaderCounter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommentsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Favorite" Member="Favorites" ThisKey="Id" OtherKey="UserId" Type="Favorite" />
      <Association Name="User_Header" Member="Headers" ThisKey="Id" OtherKey="UserId" Type="Header" />
      <Association Name="User_Message" Member="Messages" ThisKey="Id" OtherKey="ReceiverId" Type="Message" />
      <Association Name="User_Message1" Member="Messages1" ThisKey="Id" OtherKey="SenderId" Type="Message" />
      <Association Name="User_Note" Member="Notes" ThisKey="Id" OtherKey="UserId" Type="Note" />
      <Association Name="User_Poll" Member="Polls" ThisKey="Id" OtherKey="AuthorId" Type="Poll" />
      <Association Name="User_PollVote" Member="PollVotes" ThisKey="Id" OtherKey="UserId" Type="PollVote" />
      <Association Name="User_Post" Member="Posts" ThisKey="Id" OtherKey="UserId" Type="Post" />
      <Association Name="User_RatingLog" Member="RatingLogs" ThisKey="Id" OtherKey="UserId" Type="RatingLog" />
      <Association Name="User_Recovery" Member="Recoveries" ThisKey="Id" OtherKey="UserId" Type="Recovery" />
    </Type>
  </Table>
  <Table Name="dbo.Captchas" Member="Captchas">
    <Type Name="Captcha">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Captcha_CaptchaAnswer" Member="CaptchaAnswers" ThisKey="Id" OtherKey="CaptchaId" Type="CaptchaAnswer" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_PostsCategory" Member="PostsCategories" ThisKey="Id" OtherKey="CategoryId" Type="PostsCategory" />
    </Type>
  </Table>
  <Table Name="dbo.Comments" Member="Comments">
    <Type Name="Comment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Ip" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Post_Comment" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Favorites" Member="Favorites">
    <Type Name="Favorite">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Favorite" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Post_Favorite" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Headers" Member="Headers">
    <Type Name="Header" Id="ID3">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Header" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MenuItems" Member="MenuItems">
    <Type Name="MenuItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Sort" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TargetIsBlank" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Messages" Member="Messages">
    <Type Name="Message">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiverId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SenderId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeletedForReceiver" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="IsDeletedForSender" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsReceiverRead" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="User_Message" Member="User" ThisKey="ReceiverId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="User_Message1" Member="User1" ThisKey="SenderId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Notes" Member="Notes">
    <Type Name="Note">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_Note" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PollAnswers" Member="PollAnswers">
    <Type Name="PollAnswer">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="PollId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VotesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PollAnswer_PollVote" Member="PollVotes" ThisKey="Id" OtherKey="AnswerId" Type="PollVote" />
      <Association Name="Poll_PollAnswer" Member="Poll" ThisKey="PollId" OtherKey="Id" Type="Poll" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Polls" Member="Polls">
    <Type Name="Poll">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="IsMultiselect" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="AuthorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsOpen" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="VotesCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Poll_PollAnswer" Member="PollAnswers" ThisKey="Id" OtherKey="PollId" Type="PollAnswer" />
      <Association Name="Poll_PollVote" Member="PollVotes" ThisKey="Id" OtherKey="PollId" Type="PollVote" />
      <Association Name="User_Poll" Member="User" ThisKey="AuthorId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PollVotes" Member="PollVotes">
    <Type Name="PollVote">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PollId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnswerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="PollAnswer_PollVote" Member="PollAnswer" ThisKey="AnswerId" OtherKey="Id" Type="PollAnswer" IsForeignKey="true" />
      <Association Name="Poll_PollVote" Member="Poll" ThisKey="PollId" OtherKey="Id" Type="Poll" IsForeignKey="true" />
      <Association Name="User_PollVote" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Posts" Member="Posts">
    <Type Name="Post" Id="ID4">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsAttached" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ViewsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="CommentsCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Post_Comment" Member="Comments" ThisKey="Id" OtherKey="PostId" Type="Comment" />
      <Association Name="Post_Favorite" Member="Favorites" ThisKey="Id" OtherKey="PostId" Type="Favorite" />
      <Association Name="Post_PostsCategory" Member="PostsCategories" ThisKey="Id" OtherKey="PostId" Type="PostsCategory" />
      <Association Name="User_Post" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostsCategories" Member="PostsCategories">
    <Type Name="PostsCategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_PostsCategory" Member="Category" ThisKey="CategoryId" OtherKey="Id" Type="Category" IsForeignKey="true" />
      <Association Name="Post_PostsCategory" Member="Post" ThisKey="PostId" OtherKey="Id" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RatingLogs" Member="RatingLogs">
    <Type Name="RatingLog">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_RatingLog" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ratings" Member="Ratings">
    <Type Name="Rating">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EntityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntityType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Recoveries" Member="Recoveries">
    <Type Name="Recovery" Id="ID1">
      <Column Name="Guid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="User_Recovery" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rfcs" Member="Rfcs">
    <Type Name="Rfc">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.RecoveriesAdd" Method="RecoveriesAdd">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID1" />
  </Function>
  <Function Name="dbo.RecoveriesDelete" Method="RecoveriesDelete">
    <Parameter Name="guid" Type="System.String" DbType="NVarChar(1024)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.RecoveriesPurge" Method="RecoveriesPurge">
    <Parameter Name="days" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UsersUpdate" Method="UsersUpdate">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="role" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="canAddHeader" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="headerCounter" Type="System.Int32" DbType="Int" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.UsersAdd" Method="UsersAdd">
    <Parameter Name="nick" Type="System.String" DbType="NVarChar(32)" />
    <Parameter Name="password" Type="System.String" DbType="NVarChar(1024)" />
    <Parameter Name="role" Type="System.Byte" DbType="TinyInt" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(32)" />
    <ElementType IdRef="ID2" />
  </Function>
  <Function Name="dbo.HeadersDelete" Method="HeadersDelete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HeadersAdd" Method="HeadersAdd">
    <Parameter Name="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="text" Type="System.String" DbType="NVarChar(128)" />
    <Parameter Name="endDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType IdRef="ID3" />
  </Function>
  <Function Name="dbo.PostGetByCat" Method="PostGetByCat">
    <Parameter Name="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="cat_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="posts_count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType IdRef="ID4" />
  </Function>
  <Function Name="dbo.PostGet" Method="PostGet">
    <Parameter Name="page" Type="System.Int32" DbType="Int" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="posts_count" Type="System.Int32" DbType="Int" Direction="InOut" />
    <ElementType IdRef="ID4" />
  </Function>
</Database>